name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: windows-2019

    steps: 
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.17.0'
          

      - name: Run Script
        run: | 
            cd js ts day
            node js ts day/first.js
