name: Build and test

on:
  push:
    branches: main

jobs:
  build_and_test:
  runs-on: ubuntu-latest
  steps: 
      -name: checkout
      uses: actions/checkout@v2

      -name: abc
      uses: actions/setup-node@v2
      with:
        node-version:20.17.0

      -name: run script
      uses: node first.js
